[package]
name = "rustset-framework-security"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
argon2.workspace = true
axum.workspace = true
bcrypt.workspace = true
chrono.workspace = true
jsonwebtoken.workspace = true
rand_core.workspace = true
rustset-framework-common.workspace = true
serde.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
tower.workspace = true
