[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
chrono = "0.4"
shared = { path = "../shared" }
rand = "0.8"
uuid = { version = "1.0", features = ["v4"] }
ipnetwork = "0.21.1"
lazy_static = "1.4"
async-trait = "0.1"
regex = "1.10"
futures = "0.3"
async-stream = "0.3"
tokio-stream = "0.1"
