pub mod dept;
pub use dept::{SystemDeptTree, SystemMenuTree};

use crate::components::*;
use crate::services::api;
use dioxus::prelude::*;
use serde_json::{json, Value};

#[component] pub fn SystemUser() -> Element { sys_crud("user","用户管理",vec![Column{key:"username".to_string(),title:"用户名".to_string(),width:None},Column{key:"nickname".to_string(),title:"昵称".to_string(),width:None},Column{key:"email".to_string(),title:"邮箱".to_string(),width:None},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemRole() -> Element { sys_crud("role","角色管理",vec![Column{key:"code".to_string(),title:"角色编码".to_string(),width:None},Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"dataScope".to_string(),title:"数据范围".to_string(),width:Some("100px".to_string())},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemMenu() -> Element { rsx! { SystemMenuTree {} } }
#[component] pub fn SystemDept() -> Element { rsx! { SystemDeptTree {} } }
#[component] pub fn SystemPost() -> Element { sys_crud("post","岗位管理",vec![Column{key:"code".to_string(),title:"编码".to_string(),width:None},Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"sort".to_string(),title:"排序".to_string(),width:Some("80px".to_string())},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemDict() -> Element { sys_crud("dict","字典管理",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"type".to_string(),title:"类型".to_string(),width:None},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemTenant() -> Element { sys_crud("tenant","租户管理",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"contactName".to_string(),title:"联系人".to_string(),width:None},Column{key:"contactMobile".to_string(),title:"手机".to_string(),width:None},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemTenantPackage() -> Element { sys_crud("tenant-package","租户套餐",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemMailAccount() -> Element { sys_crud("mail-account","邮件账号",vec![Column{key:"mail".to_string(),title:"邮箱".to_string(),width:None},Column{key:"username".to_string(),title:"用户名".to_string(),width:None},Column{key:"host".to_string(),title:"主机".to_string(),width:None}]) }
#[component] pub fn SystemMailTemplate() -> Element { sys_crud("mail-template","邮件模板",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"code".to_string(),title:"编码".to_string(),width:None},Column{key:"nickname".to_string(),title:"发件人".to_string(),width:None}]) }
#[component] pub fn SystemNotice() -> Element { sys_crud("notice","通知公告",vec![Column{key:"title".to_string(),title:"标题".to_string(),width:None},Column{key:"type".to_string(),title:"类型".to_string(),width:Some("80px".to_string())},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemArea() -> Element { sys_crud("area","地区管理",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"code".to_string(),title:"编码".to_string(),width:Some("100px".to_string())}]) }
#[component] pub fn SystemSocialClient() -> Element { sys_crud("social-client","社交客户端",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"platform".to_string(),title:"平台".to_string(),width:Some("100px".to_string())},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemOauth2Client() -> Element { sys_crud("oauth2-client","OAuth2客户端",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"clientId".to_string(),title:"客户端ID".to_string(),width:None},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemNotifyTemplate() -> Element { sys_crud("notify-template","站内信模板",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"code".to_string(),title:"编码".to_string(),width:Some("100px".to_string())},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemSmsChannel() -> Element { sys_crud("sms-channel","短信渠道",vec![Column{key:"code".to_string(),title:"编码".to_string(),width:None},Column{key:"signature".to_string(),title:"签名".to_string(),width:None},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemSmsTemplate() -> Element { sys_crud("sms-template","短信模板",vec![Column{key:"code".to_string(),title:"编码".to_string(),width:None},Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"content".to_string(),title:"内容".to_string(),width:None}]) }
#[component] pub fn SystemOperateLog() -> Element { sys_readonly("operate-log","操作日志",vec![Column{key:"name".to_string(),title:"操作".to_string(),width:None},Column{key:"operatorType".to_string(),title:"类型".to_string(),width:Some("80px".to_string())},Column{key:"startTime".to_string(),title:"时间".to_string(),width:Some("160px".to_string())},Column{key:"duration".to_string(),title:"耗时ms".to_string(),width:Some("80px".to_string())},Column{key:"resultCode".to_string(),title:"结果".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemLoginLog() -> Element { sys_readonly("login-log","登录日志",vec![Column{key:"username".to_string(),title:"用户名".to_string(),width:None},Column{key:"userIp".to_string(),title:"IP".to_string(),width:Some("130px".to_string())},Column{key:"result".to_string(),title:"结果".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemMailLog() -> Element { sys_readonly("mail-log","邮件日志",vec![Column{key:"templateName".to_string(),title:"模板".to_string(),width:None},Column{key:"sendMail".to_string(),title:"收件人".to_string(),width:None},Column{key:"sendStatus".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemSmsLog() -> Element { sys_readonly("sms-log","短信日志",vec![Column{key:"templateName".to_string(),title:"模板".to_string(),width:None},Column{key:"mobile".to_string(),title:"手机号".to_string(),width:None},Column{key:"sendStatus".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemNotify() -> Element { sys_readonly("notify-message","我的消息",vec![Column{key:"title".to_string(),title:"标题".to_string(),width:None},Column{key:"readStatus".to_string(),title:"状态".to_string(),width:Some("80px".to_string())},Column{key:"createTime".to_string(),title:"时间".to_string(),width:Some("160px".to_string())}]) }
#[component] pub fn SystemOauth2() -> Element { sys_readonly("oauth2-client","OAuth2客户端",vec![Column{key:"name".to_string(),title:"名称".to_string(),width:None},Column{key:"clientId".to_string(),title:"客户端ID".to_string(),width:None},Column{key:"status".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemSocial() -> Element { sys_readonly("social-user","社交用户",vec![Column{key:"nickname".to_string(),title:"昵称".to_string(),width:None},Column{key:"platform".to_string(),title:"平台".to_string(),width:Some("100px".to_string())}]) }
#[component] pub fn SystemSocialUser() -> Element { sys_readonly("social-user","社交用户",vec![Column{key:"nickname".to_string(),title:"昵称".to_string(),width:None},Column{key:"platform".to_string(),title:"平台".to_string(),width:Some("100px".to_string())}]) }
#[component] pub fn SystemOauth2Token() -> Element { sys_readonly("oauth2-token","OAuth2令牌",vec![Column{key:"accessToken".to_string(),title:"令牌".to_string(),width:None},Column{key:"username".to_string(),title:"用户".to_string(),width:Some("100px".to_string())},Column{key:"expiresTime".to_string(),title:"过期时间".to_string(),width:Some("160px".to_string())}]) }
#[component] pub fn SystemNotifyMessageList() -> Element { sys_readonly("notify-message","站内信消息",vec![Column{key:"title".to_string(),title:"标题".to_string(),width:None},Column{key:"userNickname".to_string(),title:"接收人".to_string(),width:Some("100px".to_string())},Column{key:"readStatus".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }
#[component] pub fn SystemNotifyMessageId() -> Element { sys_readonly("notify-message","我的站内信",vec![Column{key:"title".to_string(),title:"标题".to_string(),width:None},Column{key:"readStatus".to_string(),title:"状态".to_string(),width:Some("80px".to_string())}]) }

fn sys_crud(module:&str,title:&str,cols:Vec<Column>)->Element{
    let m=module.to_string();let mut data=use_signal(Vec::<Value>::new);let mut total=use_signal(||0i64);let mut pg=use_signal(||1i64);let mut loading=use_signal(||true);let mut show=use_signal(||false);let mut edit_id=use_signal(||None::<String>);let mut form=use_signal(||json!({}));let mut saving=use_signal(||false);let mut keyword=use_signal(String::new);
    let load={let m=m.clone();let cols=cols.clone();move||{let m=m.clone();let kw=keyword();let sk=cols.first().map(|c|c.key.clone()).unwrap_or_else(||"name".to_string());spawn(async move{loading.set(true);if!kw.is_empty(){let path=format!("/system/{}/page?pageNo={}&pageSize=10&{}={}",m,pg(),sk,kw);if let Ok(v)=crate::services::api::get_path(&path).await{if let Some(arr)=v["data"]["list"].as_array(){data.set(arr.clone());}total.set(v["data"]["total"].as_i64().unwrap_or(0));}}else{if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}}loading.set(false);});}};
    use_effect(load);
    let on_save={let m=m.clone();move|_|{let f=form();let m=m.clone();saving.set(true);spawn(async move{let r=if edit_id().is_some(){api::sys_update(&m,f).await}else{api::sys_create(&m,f).await.map(|_|())};saving.set(false);if r.is_ok(){toast("保存成功",ToastKind::Success);show.set(false);pg.set(1);}else{toast(&format!("失败:{}",r.unwrap_err()),ToastKind::Error);}});}};
    let t=title.to_string();let dt=data();let tot=total();let p=pg();let ld=loading();let sv=saving();let sh=show();let kw=keyword();let m2=m.clone();let cols2=cols.clone();let m3=m.clone();let cols3=cols.clone();let m4=m.clone();
    rsx!{
        PageHeader{title:t,actions:rsx!{
            button{class:"ant-btn ant-btn-primary",onclick:move|_|{form.set(json!({}));edit_id.set(None);show.set(true);},"+ 新增"}
        }}
        div{class:"flex gap-2 mb-4",
            input{class:"ant-input w-[260px]",placeholder:"搜索...",value:"{kw}",oninput:move|e|keyword.set(e.value()),onkeydown:{let sk=cols2.first().map(|c|c.key.clone()).unwrap_or_else(||"name".to_string());move|e|{if e.key()==Key::Enter{let m=m2.clone();let sk=sk.clone();let kw2=keyword();spawn(async move{loading.set(true);if!kw2.is_empty(){let path=format!("/system/{}/page?pageNo={}&pageSize=10&{}={}",m,pg(),sk,kw2);if let Ok(v)=crate::services::api::get_path(&path).await{if let Some(arr)=v["data"]["list"].as_array(){data.set(arr.clone());}total.set(v["data"]["total"].as_i64().unwrap_or(0));}}else{if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}}loading.set(false);});}}}}
            button{class:"ant-btn ant-btn-primary text-sm",onclick:{let sk=cols3.first().map(|c|c.key.clone()).unwrap_or_else(||"name".to_string());move|_|{let m=m3.clone();let sk=sk.clone();let kw2=keyword();spawn(async move{loading.set(true);if!kw2.is_empty(){let path=format!("/system/{}/page?pageNo={}&pageSize=10&{}={}",m,pg(),sk,kw2);if let Ok(v)=crate::services::api::get_path(&path).await{if let Some(arr)=v["data"]["list"].as_array(){data.set(arr.clone());}total.set(v["data"]["total"].as_i64().unwrap_or(0));}}else{if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}}loading.set(false);});}},"🔍 搜索"}
            button{class:"ant-btn text-sm",onclick:move|_|{keyword.set(String::new());let m=m4.clone();spawn(async move{loading.set(true);if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}loading.set(false);});},"↺ 重置"}
        }
        DataTable{columns:cols.clone(),data:dt,loading:ld,page:p,page_size:10,total:tot,on_page_change:EventHandler::new(move|p:i64|pg.set(p)),on_edit:Some(EventHandler::new(move|id:String|{if let Some(i)=data().iter().find(|v|get_id(v)==id){form.set(i.clone());edit_id.set(Some(id));show.set(true);}})),on_delete:Some(EventHandler::new({let m=m.clone();move|id:String|{let m=m.clone();spawn(async move{let _=api::sys_remove(&m,&id).await;toast("删除成功",ToastKind::Success);});}})),extra_row:None}
        Modal{title:if edit_id().is_some(){"编辑".to_string()}else{"新增".to_string()},visible:sh,width:None,loading:sv,on_close:EventHandler::new(move|_|show.set(false)),on_save:Some(EventHandler::new(on_save)),children:{let cl=cols.clone();let items:Vec<_>=cl.iter().map(|c|{let k=c.key.clone();let l=c.title.clone();let ft=if k=="status"||k.ends_with("Status"){0}else if k.contains("sort")||k.contains("age")||k.contains("order"){1}else if k.contains("remark")||k.contains("desc")||k.contains("content")||k.contains("note")||k.contains("address"){2}else{3};match ft{0=>rsx!{FormItem{label:l.clone(),required:false,children:{let k=k.clone();rsx!{select{class:"ant-input",onchange:move|e|{let mut f=form();f[k.clone()]=json!(e.value());form.set(f);},option{value:"","请选择"}option{value:"0","启用"}option{value:"1","禁用"}}}}}},1=>rsx!{FormItem{label:l.clone(),required:false,children:{let k=k.clone();rsx!{input{class:"ant-input",r#type:"number",placeholder:"请输入{l}",oninput:move|e|{let mut f=form();f[k.clone()]=json!(e.value().parse::<i64>().unwrap_or(0));form.set(f);}}}}}},2=>rsx!{FormItem{label:l.clone(),required:false,children:{let k=k.clone();rsx!{textarea{class:"ant-input",rows:"3",placeholder:"请输入{l}",oninput:move|e|{let mut f=form();f[k.clone()]=json!(e.value());form.set(f);}}}}}},_=>rsx!{FormItem{label:l.clone(),required:false,children:{let k=k.clone();rsx!{input{class:"ant-input",placeholder:"请输入{l}",oninput:move|e|{let mut f=form();f[k.clone()]=json!(e.value());form.set(f);}}}}}}}}).collect::<Vec<_>>();rsx!{for item in items{ {item} }}}}
    }
}
fn sys_readonly(module:&str,title:&str,cols:Vec<Column>)->Element{
    let m=module.to_string();let mut data=use_signal(Vec::<Value>::new);let mut total=use_signal(||0i64);let mut pg=use_signal(||1i64);let mut loading=use_signal(||true);let mut keyword=use_signal(String::new);
    let load={let m=m.clone();let cols=cols.clone();move||{let m=m.clone();let kw=keyword();let sk=cols.first().map(|c|c.key.clone()).unwrap_or_else(||"name".to_string());spawn(async move{loading.set(true);if!kw.is_empty(){let path=format!("/system/{}/page?pageNo={}&pageSize=10&{}={}",m,pg(),sk,kw);if let Ok(v)=crate::services::api::get_path(&path).await{if let Some(arr)=v["data"]["list"].as_array(){data.set(arr.clone());}total.set(v["data"]["total"].as_i64().unwrap_or(0));}}else{if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}}loading.set(false);});}};
    use_effect(load);
    let t=title.to_string();let kw=keyword();let dt=data();let tot=total();let p=pg();let ld=loading();let m2=m.clone();let c2=cols.clone();let m3=m.clone();let c3=cols.clone();let m4=m.clone();
    rsx!{
        PageHeader{title:t,actions:None}
        div{class:"flex gap-2 mb-4",
            input{class:"ant-input w-[260px]",placeholder:"搜索...",value:"{kw}",oninput:move|e|keyword.set(e.value()),onkeydown:{let sk=c2.first().map(|c|c.key.clone()).unwrap_or_else(||"name".to_string());move|e|{if e.key()==Key::Enter{let m=m2.clone();let sk=sk.clone();let kw2=keyword();spawn(async move{loading.set(true);if!kw2.is_empty(){let path=format!("/system/{}/page?pageNo={}&pageSize=10&{}={}",m,pg(),sk,kw2);if let Ok(v)=crate::services::api::get_path(&path).await{if let Some(arr)=v["data"]["list"].as_array(){data.set(arr.clone());}total.set(v["data"]["total"].as_i64().unwrap_or(0));}}else{if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}}loading.set(false);});}}}}
            button{class:"ant-btn ant-btn-primary text-sm",onclick:{let sk=c3.first().map(|c|c.key.clone()).unwrap_or_else(||"name".to_string());move|_|{let m=m3.clone();let sk=sk.clone();let kw2=keyword();spawn(async move{loading.set(true);if!kw2.is_empty(){let path=format!("/system/{}/page?pageNo={}&pageSize=10&{}={}",m,pg(),sk,kw2);if let Ok(v)=crate::services::api::get_path(&path).await{if let Some(arr)=v["data"]["list"].as_array(){data.set(arr.clone());}total.set(v["data"]["total"].as_i64().unwrap_or(0));}}else{if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}}loading.set(false);});}},"🔍 搜索"}
            button{class:"ant-btn text-sm",onclick:move|_|{keyword.set(String::new());let m=m4.clone();spawn(async move{loading.set(true);if let Ok((l,t))=api::sys_page(&m,pg(),10).await{data.set(l);total.set(t);}loading.set(false);});},"↺ 重置"}
        }
        DataTable{columns:cols,data:dt,loading:ld,page:p,page_size:10,total:tot,on_page_change:EventHandler::new(move|p:i64|pg.set(p)),on_edit:None,on_delete:None,extra_row:None}
    }
}
