[package]
name = "rustset-media-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
rustset-framework-common.workspace = true
rustset-framework-database.workspace = true
rustset-framework-security.workspace = true
rustset-framework-web.workspace = true
rustset-media-api.workspace = true
serde_json.workspace = true
sqlx.workspace = true
uuid.workspace = true
